"""ownerId added

Revision ID: 9e0b7881c446
Revises: 3bf787c2906b
Create Date: 2024-05-03 09:13:31.745979

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e0b7881c446"
down_revision: Union[str, None] = "3bf787c2906b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notes", sa.Column("ownerId", sa.Integer(), nullable=True))
    op.drop_column("notes", "ownerID")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notes", sa.Column("ownerID", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_column("notes", "ownerId")
    # ### end Alembic commands ###
