"""image and pinfl added

Revision ID: afe23d3a1c81
Revises: 9e0b7881c446
Create Date: 2024-05-16 17:30:49.481476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afe23d3a1c81'
down_revision: Union[str, None] = '9e0b7881c446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_users', sa.Column('pinfl', sa.String(), nullable=True))
    op.add_column('note_users', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note_users', 'image')
    op.drop_column('note_users', 'pinfl')
    # ### end Alembic commands ###
