"""init

Revision ID: e850184eead5
Revises: 
Create Date: 2024-05-28 10:58:28.561264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e850184eead5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organizationId', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('fromTime', sa.Time(), nullable=True),
    sa.Column('tillTime', sa.Time(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('colorCode', sa.String(), nullable=True),
    sa.Column('isDelete', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.TIMESTAMP(), nullable=True),
    sa.Column('updatedAt', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employmentId', sa.Integer(), nullable=True),
    sa.Column('pinfl', sa.String(), nullable=True),
    sa.Column('fullName', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('noteId', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.TIMESTAMP(), nullable=True),
    sa.Column('updatedAt', sa.TIMESTAMP(), nullable=True),
    sa.Column('isOwner', sa.Boolean(), nullable=True),
    sa.Column('isDelete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['noteId'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note_users')
    op.drop_table('notes')
    # ### end Alembic commands ###
