"""note and note user table generate

Revision ID: f2355d04fbf8
Revises: 
Create Date: 2024-05-01 10:02:06.713947

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2355d04fbf8"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notes",
        sa.Column("Id", sa.Integer(), nullable=False),
        sa.Column("OrganizationId", sa.Integer(), nullable=True),
        sa.Column("Title", sa.String(), nullable=True),
        sa.Column("Date", sa.Date(), nullable=True),
        sa.Column("FromTime", sa.Time(), nullable=True),
        sa.Column("TillTime", sa.Time(), nullable=True),
        sa.Column("Location", sa.String(), nullable=True),
        sa.Column("Description", sa.Text(), nullable=True),
        sa.Column("ColorCode", sa.String(), nullable=True),
        sa.Column("IsDelete", sa.Boolean(), nullable=True),
        sa.Column("CreatedAt", sa.TIMESTAMP(), nullable=True),
        sa.Column("UpdatedAt", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("Id"),
    )
    op.create_table(
        "note_users",
        sa.Column("Id", sa.Integer(), nullable=False),
        sa.Column("UserId", sa.Integer(), nullable=True),
        sa.Column("Fullname", sa.String(), nullable=True),
        sa.Column("NoteId", sa.Integer(), nullable=True),
        sa.Column("CreatedAt", sa.TIMESTAMP(), nullable=True),
        sa.Column("UpdatedAt", sa.TIMESTAMP(), nullable=True),
        sa.Column("IsOwner", sa.Boolean(), nullable=True),
        sa.Column("IsDelete", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["NoteId"],
            ["notes.Id"],
        ),
        sa.PrimaryKeyConstraint("Id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("note_users")
    op.drop_table("notes")
    # ### end Alembic commands ###
